# Support script for GraphViz option file generation
#
# Since migrating the vcpkg, ALL boost libraries are now listed as imported targets
# and this has the affect of polluting the generated dependency graphs. As a workaround,
# this script will strip out boost dependencies in the output unless they have been
# directly linked by at least one project. The following strategy is used:
#  * generate a list of boost libraries that have been referenced by at least one build
#    system target
#  * generate a list of all imported boost libraries
#  * strip out referenced libraries from the imported list
#  * whatever is left over will be ignored by the dependency graph generator

# get all direct dependencies to the boost library
set(__all_boost_project_links)
function(__get_all_boost_project_links __dir)
    get_property(__targets DIRECTORY "${__dir}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(__target ${__targets})
        get_target_property(__links ${__target} LINK_LIBRARIES)
        if(NOT __links STREQUAL "__links-NOTFOUND")
            foreach(__link ${__links})
                if (__link MATCHES "^Boost::")
                    if (NOT __link IN_LIST __all_boost_project_links)
                        list(APPEND __all_boost_project_links "${__link}")
                    endif()
                endif()
            endforeach()
        endif()
    endforeach()
    get_property(__subdirs DIRECTORY "${__dir}" PROPERTY SUBDIRECTORIES)
    foreach(__subdir ${__subdirs})
        __get_all_boost_project_links("${__subdir}")
    endforeach()
    set(__all_boost_project_links ${__all_boost_project_links} PARENT_SCOPE)
endfunction()
__get_all_boost_project_links("${CMAKE_SOURCE_DIR}")
unset(__targets)
unset(__target)
unset(__links)
unset(__link)
unset(__subdirs)
unset(__subdir)

# get all boost targets
set(__all_boost_targets)
function(__get_all_boost_targets __dir)
    get_property(__targets DIRECTORY "${__dir}" PROPERTY IMPORTED_TARGETS)
    foreach(__target ${__targets})
        if (__target MATCHES "^Boost::")
            list(APPEND __all_boost_targets "${__target}")
        endif()
    endforeach()
    get_property(__subdirs DIRECTORY "${__dir}" PROPERTY SUBDIRECTORIES)
    foreach(__subdir ${__subdirs})
        __get_all_boost_targets("${__subdir}")
    endforeach()
    set(__all_boost_targets ${__all_boost_targets} PARENT_SCOPE)
endfunction()
__get_all_boost_targets("${CMAKE_SOURCE_DIR}")
unset(__targets)
unset(__target)
unset(__subdirs)
unset(__subdir)

# make a copy of the boost target list, remove all directly linked targets from it
set(__graphviz_boost_ignore_list "${__all_boost_targets}")
foreach(__link in ${__all_boost_project_links})
    list(REMOVE_ITEM __graphviz_boost_ignore_list "${__link}")
endforeach()
list(SORT __graphviz_boost_ignore_list)
unset(__link)
unset(__all_boost_targets)
unset(__all_boost_project_links)

# update CMakeGraphVizOptions.cmake in this folder
# (it seems that the GraphViz tool only accepts settings files, not files with code)
file(WRITE "${CMAKE_CURRENT_SOURCE_DIR}/CMakeGraphVizOptions.cmake" "# See https://cmake.org/cmake/help/latest/module/CMakeGraphVizOptions.html for details of options.\n")
file(APPEND "${CMAKE_CURRENT_SOURCE_DIR}/CMakeGraphVizOptions.cmake" "\n")
file(APPEND "${CMAKE_CURRENT_SOURCE_DIR}/CMakeGraphVizOptions.cmake" "# IMPORTANT: This file is automatically generated by the build script (see CMake/IMP_GenerateGraphVizOptions.cmake for more information)\n")
file(APPEND "${CMAKE_CURRENT_SOURCE_DIR}/CMakeGraphVizOptions.cmake" "\n")
file(APPEND "${CMAKE_CURRENT_SOURCE_DIR}/CMakeGraphVizOptions.cmake" "# Set to FALSE to exclude unknown libraries from the generated graphs.\n")
file(APPEND "${CMAKE_CURRENT_SOURCE_DIR}/CMakeGraphVizOptions.cmake" "set(GRAPHVIZ_UNKNOWN_LIBS FALSE)\n")
file(APPEND "${CMAKE_CURRENT_SOURCE_DIR}/CMakeGraphVizOptions.cmake" "\n")
file(APPEND "${CMAKE_CURRENT_SOURCE_DIR}/CMakeGraphVizOptions.cmake" "# A list of regular expressions for names of targets to exclude from the generated graphs.\n")
file(APPEND "${CMAKE_CURRENT_SOURCE_DIR}/CMakeGraphVizOptions.cmake" "set(GRAPHVIZ_IGNORE_TARGETS \".lib;synchronization;${__graphviz_boost_ignore_list}\")\n")
unset(__graphviz_boost_ignore_list)
