function(export_dependencies_as_json json_file)
    # part 1: get a list of all targets and save to __all_targets
    set(__all_targets)
    function(__target_metadata_get_directory_targets __dir)
        get_property(__targets DIRECTORY "${__dir}" PROPERTY BUILDSYSTEM_TARGETS)
        foreach(__target ${__targets})
            list(APPEND __all_targets "${__target}")
        endforeach()
        get_property(__subdirs DIRECTORY "${__dir}" PROPERTY SUBDIRECTORIES)
        foreach(__subdir ${__subdirs})
            __target_metadata_get_directory_targets("${__subdir}")
        endforeach()
        set(__all_targets ${__all_targets} PARENT_SCOPE)
    endfunction()
    __target_metadata_get_directory_targets("${CMAKE_SOURCE_DIR}")
    list(SORT __all_targets)
    list(LENGTH __all_targets __target_count)
    message(STATUS "There are ${__target_count} targets")

    # part 2: create an imp_targets.json file in the output folder containing all pertinent target information
    file(WRITE ${json_file} "{\n")
    file(APPEND ${json_file} "    \"targets\" : [\n")
    set(__first_target ON)
    foreach(__target ${__all_targets})
        get_target_property(__type ${__target} TYPE)
        if(NOT __first_target)
            file(APPEND ${json_file} ",\n")
        endif()
        if(__type STREQUAL "INTERFACE_LIBRARY")
            unset(__root)
            unset(__sources)
            get_target_property(__includes ${__target} INTERFACE_INCLUDE_DIRECTORIES)
            get_target_property(__links ${__target} INTERFACE_LINK_LIBRARIES)
        else()
            get_target_property(__root ${__target} SOURCE_DIR)
            file(RELATIVE_PATH __root ${CMAKE_SOURCE_DIR} ${__root})
            get_target_property(__sources ${__target} SOURCES)
            get_target_property(__includes ${__target} INCLUDE_DIRECTORIES)
            get_target_property(__links ${__target} LINK_LIBRARIES)
        endif()
        list(SORT __links)
        # begin target fragment
        file(APPEND ${json_file} "        {\n")
        file(APPEND ${json_file} "            \"name\" : \"${__target}\",\n")
        file(APPEND ${json_file} "            \"type\" : \"${__type}\",\n")
        if(DEFINED __root)
            file(APPEND ${json_file} "            \"target_root\" : \"${__root}\",\n")
        endif()
        # export sources
        if(DEFINED __sources)
            file(APPEND ${json_file} "            \"sources\" : [\n")
            set(__first ON)
            if(NOT __sources STREQUAL "__sources-NOTFOUND")
                foreach(__source ${__sources})
                    if(NOT __first)
                        file(APPEND ${json_file} ",\n")
                    endif()
                    file(APPEND ${json_file} "                \"${__source}\"")
                    set(__first OFF)
                endforeach()
            endif()
            if(NOT __first)
                file(APPEND ${json_file} "\n")
            endif()
            file(APPEND ${json_file} "            ],\n")
        endif()
        # export include paths
        file(APPEND ${json_file} "            \"include_paths\" : [\n")
        set(__first ON)
        if(NOT __includes STREQUAL "__includes-NOTFOUND")
            foreach(__include ${__includes})
                if(NOT __include MATCHES "<TARGET_PROPERTY.*>")
                    if(NOT __first)
                        file(APPEND ${json_file} ",\n")
                    endif()
                    file(RELATIVE_PATH __include ${CMAKE_SOURCE_DIR} ${__include})
                    file(APPEND ${json_file} "                \"${__include}\"")
                    set(__first OFF)
                endif()
            endforeach()
        endif()
        if(NOT __first)
            file(APPEND ${json_file} "\n")
        endif()
        file(APPEND ${json_file} "            ],\n")
        # export links
        file(APPEND ${json_file} "            \"links\" : [\n")
        set(__first ON)
        if(NOT __links STREQUAL "__links-NOTFOUND")
            foreach(__link ${__links})
                if(NOT (__link MATCHES "^(ws2_32|dl|-pthread)$"))  # remove implicit links to system libraries
                    get_target_property(__link_type ${__link} TYPE)
                    list(FIND IMP_COTS_LIST ${__link} __link_cots_check)
                    if(__link_cots_check EQUAL -1)
                        if(NOT __first)
                            file(APPEND ${json_file} ",\n")
                        endif()
                        file(APPEND ${json_file} "                \"${__link}\"")
                        set(__first OFF)
                    endif()
                endif()
            endforeach()
        endif()
        if(NOT __first)
            file(APPEND ${json_file} "\n")
        endif()
        file(APPEND ${json_file} "            ]\n")
        # end target fragment
        file(APPEND ${json_file} "        }")
        set(__first_target OFF)
    endforeach()
    if(NOT __first_target)
        file(APPEND ${json_file} "\n")
    endif()
    file(APPEND ${json_file} "    ]\n")
    file(APPEND ${json_file} "}\n")
    message(STATUS "Exported dependencies to JSON file: ${json_file}")
endfunction()
