/*
   The copyright to the computer program(s) herein is the property of
   Dover Motion, Inc. This file is subject to the terms and
   conditions found in the 'DoverLicense.txt' file included with this
   source code package.
*/

/*!
 *  @brief   Defines the static interface used to raise alerts on both the SSC and CC
 *
 *           It is defined like this because you want clients to always be able to 'raise alerts' even if the
 *           comms and other required infrastructure is not up. If the actual impl has not been registered yet
 *           then some default/backup behaviour is executed
 */
#pragma once

#include <memory>

namespace imp
{

class IDispatcher;
using IDispatcherSPtr = std::shared_ptr<IDispatcher>;
class IAlertDetailer;
using IAlertDetailerSPtr = std::shared_ptr<IAlertDetailer>;


/*!
 * @class   Alerts
 * @brief   A static convenience interface for creating and destroying the
 *          Alerts components.
 */
class Alerts
{
public:
    Alerts() = delete;

    /*!
     * @brief   Create the Alerts components - AlertDistribution and AlertReporter, using the default AlertDetailer which
     *          details all the alerts generated by the platform.
     *
     * @param [in] pDispatcher    The dispatcher used by the AlertDistribution to perform alert raised/cleared callbacks on.
     */
    static void Create( IDispatcherSPtr pDispatcher );

    /*!
     * @brief   Create the Alerts components - AlertDistribution and AlertReporter, using the supplied AlertDetailer.
     *
     * @param [in] pDispatcher    The dispatcher used by the AlertDistribution to perform alert raised/cleared callbacks on.
     * @param [in] pAlertDetailer The alerts detailer to use when reporting alerts.
     */
    static void Create( IDispatcherSPtr pDispatcher, IAlertDetailerSPtr pAlertDetailer );

    /*!
     * @brief   Destroy the Alerts components - AlertDetailer, AlertDistribution and AlertReporter.
     */
    static void Destroy();
};

} //  namespace imp
