/*
   The copyright to the computer program(s) herein is the property of
   Dover Motion, Inc. This file is subject to the terms and
   conditions found in the 'DoverLicense.txt' file included with this
   source code package.
*/

// clang-format off

/*
   This file is autogenerated. Do not modify by hand.
*/


#pragma once

#include "AlertTypes.h"
#include <Enum.h>

namespace imp
{

namespace AxisDeviceAlertCode
{
enum Enum : Alert::AlertCode
{
    AXIS_DEVICE_ALERT_INVALID_CONFIGURATION  = 10001, // Severity =  High          , Description = Invalid configuration detected for axis device
    AXIS_DEVICE_ALERT_UNSUPPORTED_MODEL_TYPE = 10002, // Severity =  High          , Description = Unsupported axis device model type
    AXIS_DEVICE_ALERT_ALREADY_CONFIGURED     = 10003, // Severity =  High          , Description = Detected attempt to configure the axis device more than once
    AXIS_DEVICE_ALERT_POSITION_ERROR         = 10004, // Severity =  High          , Description = Position error encountered on the axis device
    AXIS_DEVICE_ALERT_GENERAL_ERROR          = 10005, // Severity =  High          , Description = General axis error detected
    AXIS_DEVICE_ALERT_SETTING_ERROR          = 10006, // Severity =  High          , Description = Bad axis setting encountered
    AXIS_DEVICE_ALERT_BUMP                   = 10007, // Severity =  High          , Description = Axis bump detected
    AXIS_DEVICE_ALERT_HALT                   = 10008, // Severity =  High          , Description = Axis halted
    AXIS_DEVICE_ALERT_ESTOP                  = 10009, // Severity =  High          , Description = Axis device ESTOPPED
    AXIS_DEVICE_ALERT_UNINITIALIZED          = 10010, // Severity =  High          , Description = Axis device not initialized
    AXIS_DEVICE_ALERT_BUSY                   = 10011, // Severity =  High          , Description = Operation requested on a busy axis device
    AXIS_DEVICE_ALERT_OUT_OF_RANGE           = 10012, // Severity =  High          , Description = Out of range error detected for axis
    AXIS_DEVICE_ALERT_CALL_INHIBITED         = 10013, // Severity =  High          , Description = Call to axis inhibited
    AXIS_DEVICE_ALERT_OVER_TEMPERATURE       = 10014, // Severity =  High          , Description = The axis motor temperature has exceeded the temperature limit
    AXIS_DEVICE_ALERT_CURRENT_FOLDBACK       = 10015, // Severity =  High          , Description = The axis motor amplifier current output has gone into a foldback condition
    AXIS_DEVICE_ALERT_OVER_VOLTAGE           = 10016, // Severity =  High          , Description = The axis motor bus voltage has exceeded the maximum bus voltage limit
    AXIS_DEVICE_ALERT_UNDER_VOLTAGE          = 10017, // Severity =  High          , Description = The axis motor bus voltage has gone below the minimum bus voltage limit
    AXIS_DEVICE_COMMUNICATIONS_FAILURE       = 10018, // Severity =  High          , Description = Communications has been lost to the axis
    LAST_ENUM = 18
}; // enum Enum
VARNUM_FUNCTIONS_DECL
} // enum namespace AxisDeviceAlertCode
} // namespace imp
