/*
   The copyright to the computer program(s) herein is the property of
   Dover Motion, Inc. This file is subject to the terms and
   conditions found in the 'DoverLicense.txt' file included with this
   source code package.
*/

// clang-format off

/*
   This file is autogenerated. Do not modify by hand.
*/


#pragma once

#include "BaseAlertDetailer.h"

namespace imp
{
class ImpAlertDetailer : public imp::BaseAlertDetailer
{
public:
    ImpAlertDetailer() = default;
    ~ImpAlertDetailer() override = default;

    void Configure() override;
};

} // namespace imp
