/*
   The copyright to the computer program(s) herein is the property of
   Dover Motion, Inc. This file is subject to the terms and
   conditions found in the 'DoverLicense.txt' file included with this
   source code package.
*/

#pragma once

#include "DateTimeFormat.h"

#include <cstdint>
#include <ostream>
#include <string>

namespace imp
{

class MonotonicTimestamp;

/*!
 * @brief   Write the timestamp as UTC using default formatting to the provided
 *          output stream.
 * @details Equivalent to os << utc_str().
 * @param[in]   os  The output stream being written to.
 * @param[in]   ts  The MonotonicTimestamp to write..
 * @returns The modified output stream.
 */
std::ostream& operator<<( std::ostream& os, MonotonicTimestamp ts );

/*!
 * @brief   Provides the system-wide monotonic clock reference.
 */
class MonotonicClock
{
public:
    /*!
     * @brief   Return the current Monotonic clock time.
     * @returns The current Monotonic clock time.
     */
    static MonotonicTimestamp now();

    /*!
     * @brief     Sleep for the specified duration in microseconds.
     * @details   This implementation is guaranteed to be unaffected by changes to
     *            the system clock during the sleep period. For this reason it
     *            must be used in preference to a direct call to any other library
     *            sleep function.
     * @param[in] durationInMicroseconds     The duration to sleep in microseconds.
     */
    static void SleepForMicroseconds( uint64_t durationInMicroseconds );

    /*!
     * @brief     Sleep for the specified duration in milliseconds.
     * @details   This implementation is guaranteed to be unaffected by changes to
     *            the system clock during the sleep period. For this reason it
     *            must be used in preference to a direct call to any other library
     *            sleep function.
     * @param[in] durationInMilliseconds     The duration to sleep in milliseconds.
     */
    static void SleepForMilliseconds( uint64_t durationInMilliseconds );

    /*!
     * @brief     Sleep for the specified duration in seconds.
     * @details   This implementation is guaranteed to be unaffected by changes to
     *            the system clock during the sleep period. For this reason it
     *            must be used in preference to a direct call to any other library
     *            sleep function.
     * @param[in] durationInSeconds     The duration to sleep in seconds.
     */
    static void SleepForSeconds( uint64_t durationInSeconds );
};

/*!
 * @brief   A monotonic timestamp. Generated by MonotonicClock.
 */
class MonotonicTimestamp
{
public:
    /*! @brief Constructor. */
    explicit MonotonicTimestamp( uint64_t microSeconds );
    /*! @brief Default Destructor. */
    ~MonotonicTimestamp() = default;

public:
    /*!
     * @brief   Return the timestamp in microseconds.
     * @details Rounds to the nearest microsecond.
     * @returns The number of microseconds since epoch.
     */

    uint64_t us() const;
    /*!
     * @brief   Return the timestamp in milliseconds.
     * @details Rounds to the nearest millisecond.
     * @returns The number of milliseconds since epoch.
     */
    uint64_t ms() const;

    /*!
     * @brief   Return the timestamp in seconds.
     * @details Rounds to the nearest second.
     * @returns The number of seconds since epoch.
     */
    uint64_t s() const;

    /*!
     * @brief   Return the timestamp as a formatted string, in UTC.
     * @details String will be suffixed by 'Z' as per ISO format.
     * @param format C print style datetime format with an additional rule: %SSS for millisecond.
     * @returns The timestamp in UTC using default formatting.
     */
    std::string utc_str( const std::string& format = DateTimeFormat::DefaultTimeStringFormat ) const;

    /*!
     * @brief   Return the timestamp as a formatted string, in local time.
     * @param format C print style datetime format with an additional rule: %SSS for millisecond.
     * @returns The timestamp in local time using default formatting.
     */
    std::string local_str( const std::string& format = DateTimeFormat::DefaultTimeStringFormat ) const;

private:
    uint64_t m_microseconds;
};

} //  namespace imp
