/*
   The copyright to the computer program(s) herein is the property of
   Dover Motion, Inc. This file is subject to the terms and
   conditions found in the 'DoverLicense.txt' file included with this
   source code package.
*/

// clang-format off

/*
   This file is autogenerated. Do not modify by hand.
*/


#pragma once

#include "AlertTypes.h"
#include <Enum.h>


namespace MotionSynergyAPIAlertCode
{
enum Enum : Alert::AlertCode
{
    Success                        = 0    , // Severity =  Low           , Description = Indicates a command has completed successfully. This will not result in an alert being raised.
    StdException                   = 30000, // Severity =  High          , Description = Indicates the command failed due to a C++ std::exception being thrown
    BoostException                 = 30001, // Severity =  High          , Description = Indicates the command failed due to a C++ boost::exception being thrown
    UnknownException               = 30002, // Severity =  SafetyCritical, Description = Indicates the command failed due to an unknown exception being thrown
    ManagedException               = 30003, // Severity =  High          , Description = Indicates the command failed due to a managed exception being thrown
    ExecuteScriptError             = 30004, // Severity =  High          , Description = The script has encountered an error during execution. Refer to the log for more details.
    PropertyErrorHigh              = 30005, // Severity =  High          , Description = An unknown High severity error has occurred while reading an interface property. The software will need to be re-initialized.
    PropertyErrorSafetyCritical    = 30006, // Severity =  SafetyCritical, Description = An unknown Safety Critical severity error has occurred while reading an interface property. The software will need to be restarted.
    UnhandledExceptionOnDispatcher = 30007, // Severity =  SafetyCritical, Description = An unhandled exception has been caught by a Dispatcher thread causing it to exit.
    FailedToInitialize             = 30008, // Severity =  High          , Description = Initialization of the hardware subsystem failed. The software will need to be re-initialized.
    ScriptNotFoundError            = 30009, // Severity =  Medium        , Description = A script file matching the supplied script name does not exist.
    ScriptAborted                  = 30010, // Severity =  Medium        , Description = A script was aborted during execution.
    LAST_ENUM = 12
}; // enum Enum
VARNUM_FUNCTIONS_DECL
} // enum namespace MotionSynergyAPIAlertCode
