/*
   The copyright to the computer program(s) herein is the property of
   Dover Motion, Inc. This file is subject to the terms and
   conditions found in the 'DoverLicense.txt' file included with this
   source code package.
*/

// clang-format off

/*
   This file is autogenerated. Do not modify by hand.
*/


#pragma once

#include "AlertTypes.h"
#include <Enum.h>

namespace imp
{

namespace SystemAlertCode
{
enum Enum : Alert::AlertCode
{
    AlertsRaisedBeforeReporter               = 1    , // Severity =  Low           , Description = An alert was raised by a component in the SCP before a connection to the CCP had been established
    NoConnectionToScp                        = 2    , // Severity =  SafetyCritical, Description = The CCP could not establish a connection to the SCP
    LAST_ENUM = 2
}; // enum Enum
VARNUM_FUNCTIONS_DECL
} // enum namespace SystemAlertCode
} // namespace imp
